"""Write the named-principal results (install and held-out pairs) as markdown from results/analysis_real.json, so the README table cannot drift from the data.
Rounding is half up. Output: docs/NAMED_RESULTS.md and the block between the NAMED markers in README.md."""
import json, os
from decimal import Decimal, ROUND_HALF_UP
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def rd(x, d=2): return str(Decimal(repr(float(x))).quantize(Decimal(1).scaleb(-d), rounding=ROUND_HALF_UP))
def sg(x): return ("+" if x >= 0 else "-") + rd(abs(x))
def pv(p): return "<0.001" if p < 0.001 else rd(p, 3)

def table(path, title):
    an = json.load(open(path)); L = [f"**{title}** (layer {an['layer']}, strength {an['alpha']:g}; Holm over the {an['multiplicity']['family_size']} held-out tests)", "",
                                      "| Principal | Arm (pair) | Shift | 95% CI | p vs clean (Holm) | Random band | p vs band (Holm) |", "|---|---|---|---|---|---|---|"]
    for pn, pr in an["principals"].items():
        for pair, d in pr["install"].items():
            L.append(f"| {pn} | install {pair.replace(' vs ', '/')} | {sg(d['mean_shift'])} | [{rd(d['ci95'][0])}, {rd(d['ci95'][1])}] | {pv(d['p_value'])} | [{rd(d['random_null_band95'][0])}, {rd(d['random_null_band95'][1])}] | {pv(d['p_vs_random_null'])} |")
        for pair, d in pr["branch"].items():
            ph, pb = d.get("holm_p_vs_clean"), d.get("holm_p_vs_random_null")
            L.append(f"| {pn} | {'branch (negative control)' if pn == 'Uruguay' else 'held-out branch'} {pair.replace(' vs ', '/')} | {sg(d['mean_shift_vs_clean'])} | [{rd(d['ci95'][0])}, {rd(d['ci95'][1])}] | "
                     f"{pv(d['p_vs_clean'])}" + (f" ({pv(ph)})" if ph is not None else "") + f" | [{rd(d['random_null_band95'][0])}, {rd(d['random_null_band95'][1])}] | {pv(d['p_vs_random_null'])}" + (f" ({pv(pb)})" if pb is not None else "") + " |")
    return "\n".join(L)

md = table(os.path.join(ROOT, "results", "analysis_real.json"), "Qwen3-0.6B") + "\n\n" + table(os.path.join(ROOT, "results", "qwen25_1p5b", "analysis_real.json"), "Qwen2.5-1.5B-Instruct") + "\n"
open(os.path.join(ROOT, "docs", "NAMED_RESULTS.md"), "w").write("# Named-principal results (original audit)\n\nGenerated by `src/make_named_table.py` from `results/analysis_real.json`. The random band is the 95% range of shifts from random directions of the same size.\n\n" + md)
p = os.path.join(ROOT, "README.md"); s = open(p).read()
a, b = s.index("<!-- NAMED:START -->"), s.index("<!-- NAMED:END -->")
open(p, "w").write(s[:a] + "<!-- NAMED:START -->\n" + md + s[b:])
print(md[:900])
